Ghandi/Ghandi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include(('contabilidad.urls','contabilidad') ,namespace='contabilidad')),
    path('menu/', include(('clientes.urls', 'clientes'), namespace=   'clientes')),
    path('menu/', include(('animales.urls', 'animales'), namespace='animales')),
    path('menu/', include(('logistica.urls', 'logistica'), namespace='logistica')),
    path('menu/', include(('rh.urls', 'rh'), namespace='rh'))
]

Ghandi/login/urls.py
from django.urls import path, include
from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index_login'),
    path('login/', views.login, name='login'),
    path('menu/', views.menu, name="menu"),
    path('logout/',views.logout, name="logout")
]

Ghandi/rh/urls.py
from django.urls import path, include
from . import views
app_name = 'rh'
urlpatterns = [
    path('rh/', views.menu_rh, name='menu_rh'),
    path('rh/alta_contrato', views.alta_contrato, name='alta_contrato'),
    path('rh/baja_contrato', views.baja_contrato, name='baja_contrato'),
    path('rh/agendar_entrevista', views.agendar_entrevista, name='agendar_entrevista'),
    path('rh/consultar_contrato', views.consultar_contrato, name='consultar_contrato'),
    path('rh/modificar_contrato', views.modificar_contrato, name='modificar_contrato')
]

Ghandi/login/models.py
from django.db import models

# Create your models here.

Ghandi/rh/models.py
from django.db import models

# Create your models here.

Ghandi/login/forms.py
from django import forms

class LoginBDForm(forms.Form):
   username = forms.CharField(
                  label="Nombre de Usuario",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce nombre de usuario"}))
   password = forms.CharField(
                  label="Contraseña",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce contraseña"}))

Ghandi/rh/forms.py
from django import forms

class ContratoForm(forms.Form):
    dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del empleado"}))
    nombre = forms.CharField(label="Nombre",widget=forms.TextInput(attrs={'placeholder': "Nombre del empleado"}))
    apellidos = forms.CharField(label="Apellidos",widget=forms.TextInput(attrs={'placeholder': "Apellidos"}))
    fecha_nacimiento = forms.DateField(label="FechaNacimiento", widget=forms.TextInput(attrs={'placeholder': "Fecha de nacimiento (MM/DD/YYYY)"}))
    telefono = forms.CharField(label="Telefono", widget=forms.TextInput(attrs={'placeholder': "Telefono"}))
    sueldo = forms.FloatField(label="Sueldo", widget=forms.TextInput(attrs={'placeholder': "Sueldo"}))
    cuenta_bancaria = forms.CharField(label="CuentaBancaria",widget=forms.TextInput(attrs={'placeholder': "CuentaBancaria"}))
    duracion_contrato = forms.CharField(label="Duracion",widget=forms.TextInput(attrs={'placeholder': "Durancion del contrato"}))

class DNIForm(forms.Form):
    dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del empleado"}))

class EntrevistaForm(forms.Form):
    dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del empleado"}))
    nombre = forms.CharField(label="Nombre",widget=forms.TextInput(attrs={'placeholder': "Nombre"}))
    apellidos = forms.CharField(label="Apellidos",widget=forms.TextInput(attrs={'placeholder': "Apellidos"}))
    fecha = forms.DateField(label="Fecha", widget=forms.TextInput(attrs={'placeholder': "Fecha de la entrevista (MM/DD/YYYY)"}))
    hora = forms.CharField(label="Hora",widget=forms.TextInput(attrs={'placeholder': "Hora (HH:MM)"}))

class ModificaForm(forms.Form):
    dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del empleado a modificar"}))
    nombre = forms.CharField(label="Nombre",widget=forms.TextInput(attrs={'placeholder': "Nombre nuevo"}))
    apellidos = forms.CharField(label="Apellidos",widget=forms.TextInput(attrs={'placeholder': "Apellidos nuevos"}))
    fecha_nacimiento = forms.DateField(label="FechaNacimiento", widget=forms.TextInput(attrs={'placeholder': "Fecha de nacimiento (MM/DD/YYYY)"}))
    telefono = forms.CharField(label="Telefono", widget=forms.TextInput(attrs={'placeholder': "Telefono"}))
    sueldo = forms.FloatField(label="Sueldo", widget=forms.TextInput(attrs={'placeholder': "Sueldo"}))
    cuenta_bancaria = forms.CharField(label="CuentaBancaria",widget=forms.TextInput(attrs={'placeholder': "CuentaBancaria"}))
    duracion_contrato = forms.CharField(label="Duracion",widget=forms.TextInput(attrs={'placeholder': "Durancion del contrato"}))

Ghandi/login/views.py
#from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
import datetime
from datetime import datetime as dt
from datetime import timedelta
from .forms import LoginBDForm

from . import bd

import cx_Oracle
#bd = 0

def index(request):
    return render(request, "base.html")

def login(request):
    if request.method == 'POST':
        form = LoginBDForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            try:
                #global bd # para poder usar la variable global, ha de invocarse
                bd.ConnectionBD().establecer_conexion(username, password)
                print("EStableciendo conexion: ", username, password)
                # si se ha conectado bien a la BD, lo redireccionamos  a la url del menú principal de la aplicación
                return redirect("login:menu")
            except:
                 error_message="ERROR: Credenciales de usuario y contraseña incorrectas para la conexión a la base de datos de Oracle"
                 return render(request,"login.html", {"form": form, "error_message": error_message})

    # si no se ha hecho un post o hay errores en los campos del form, se presenta de nuevo el formulario vacío para rellenarlo
    return render(request,"login.html", {"form": LoginBDForm()})



    
    



def menu(request):
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
            # Obtengo las claves del diccionario request.POST, que por ejemplo tiene el valor:
            # <QueryDict: {'csrfmiddlewaretoken': ['CHNZtCiLbU'], 'alamcen-btn': ['']}> 
            # Me quedo con las claves para coger "almacen-btn", que es la que me interesa 
            # coger (según el boton que pulse y se escoja hacer una acción u otra)
        if 'clientes-btn' in keys_request_POST:
            return HttpResponseRedirect("clientes")
        elif 'contabilidad-btn' in keys_request_POST:
            return HttpResponseRedirect("contabilidad")
        elif 'logistica-btn' in keys_request_POST:
            return HttpResponseRedirect("logistica")
        elif 'animales-btn' in keys_request_POST:
            return HttpResponseRedirect("animales")
        elif 'rh-btn' in keys_request_POST:
            return HttpResponseRedirect("rh")
        elif 'cerrar-btn' in keys_request_POST:
            return logout(request)
    return render(request, 'menu.html')



def logout(request):
    bd.ConnectionBD().cerrar_conexion()
    return HttpResponseRedirect("/")

Ghandi/rh/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages

from login import bd 
from .forms import *

import cx_Oracle

def menu_rh(request):
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
        
        if 'alta_contrato-btn' in keys_request_POST:
            return redirect("rh:alta_contrato")
        elif 'baja_contrato-btn' in keys_request_POST:
            return redirect("rh:baja_contrato")
        elif 'agendar_entrevista-btn' in keys_request_POST:
            return redirect("rh:agendar_entrevista")
        elif 'consultar_contrato-btn' in keys_request_POST:
            return redirect("rh:consultar_contrato")
        elif 'modificar_contrato-btn' in keys_request_POST:
            return redirect("rh:modificar_contrato")
        
    return render(request, 'menu_rh.html')

def alta_contrato(request):
    form = ContratoForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            dni = form.cleaned_data["dni"]
            nombre = form.cleaned_data["nombre"]
            apellidos = form.cleaned_data["apellidos"]
            fecha_nacimiento = form.cleaned_data["fecha_nacimiento"]
            telefono = form.cleaned_data["telefono"]
            sueldo = form.cleaned_data["sueldo"]
            cuenta_bancaria = form.cleaned_data["cuenta_bancaria"]
            duracion_contrato = form.cleaned_data["duracion_contrato"]  
            try:
                with bd.ConnectionBD().get_conexion().cursor() as cursor:
                    # Comprobamos si el DNI ya existe
                    sql = "SELECT * FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
                    cursor.execute(sql)
                    
                    if cursor.fetchone() is not None:
                        messages.error(request, '[ERROR] Ya existe un contrato asociado al DNI ingresado')
                        return render(request,"alta_contrato.html", {"form": form})
                    else:                        
                        sql = "INSERT INTO CONTRATO VALUES ('{0}', '{1}', '{2}', TO_DATE('{3}','YYYY-DD-MM'), '{4}', '{5}', '{6}', '{7}')".format(str(dni), str(nombre), str(apellidos), str(fecha_nacimiento), str(telefono), str(sueldo), str(cuenta_bancaria), str(duracion_contrato))
                        cursor.execute(sql)
                        bd.ConnectionBD().get_conexion().commit()
                        messages.success(request, '[INFO] Contrato guardado correctamente')
            except:
                messages.error(request, '[ERROR] Fallo al guardar el contrato')
                return render(request,"alta_contrato.html", {"form": form})
                
    return render(request, 'alta_contrato.html',{'form':form})


def baja_contrato(request):
    form = DNIForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            dni = form.cleaned_data["dni"]

            try:
                with bd.ConnectionBD().get_conexion().cursor() as cursor:
                    # Comprobamos si el DNI existe
                    sql = "SELECT * FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
                    cursor.execute(sql)
                    
                    if cursor.fetchone() is None:
                        messages.error(request, '[ERROR] No existe un contrato asociado al DNI ingresado')
                        return render(request,"baja_contrato.html", {"form": form})
                    else:                        
                        sql = "DELETE FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
                        cursor.execute(sql)
                        bd.ConnectionBD().get_conexion().commit()
                        messages.success(request, '[INFO] Contrato eliminado correctamente')
            except:
                messages.error(request, '[ERROR] Fallo al eliminar el contrato')
                return render(request,"baja_contrato.html", {"form": form})
            
    return render(request, 'baja_contrato.html',{'form':form})

def agendar_entrevista(request):
    form = EntrevistaForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            dni = form.cleaned_data["dni"]
            nombre = form.cleaned_data["nombre"]
            apellidos = form.cleaned_data["apellidos"]
            fecha = form.cleaned_data["fecha"]
            hora = form.cleaned_data["hora"]
 
            try:
                with bd.ConnectionBD().get_conexion().cursor() as cursor:
                    # Comprobamos si el DNI ya existe
                    sql = "SELECT * FROM ENTREVISTA WHERE DNI = '{0}'".format(str(dni))
                    cursor.execute(sql)
                    
                    if cursor.fetchone() is not None:
                        messages.error(request, '[ERROR] Ya existe una entrevista asociada al DNI ingresado')
                        return render(request,"agendar_entrevista.html", {"form": form})
                    else:                        
                        sql = "INSERT INTO ENTREVISTA VALUES ('{0}', '{1}', '{2}', TO_DATE('{3}','YYYY-DD-MM'), '{4}')".format(str(dni), str(nombre), str(apellidos), str(fecha), str(hora))
                        cursor.execute(sql)
                        bd.ConnectionBD().get_conexion().commit()
                        messages.success(request, '[INFO] Entrevista guardada correctamente')
            except:
                messages.error(request, '[ERROR] Fallo al guardar la entrevista')
                return render(request,"agendar_entrevista.html", {"form": form})
            
    return render(request, 'agendar_entrevista.html',{'form':form})

def consultar_contrato(request):
    form = DNIForm(request.POST)
    
    cursor = bd.ConnectionBD().get_conexion().cursor()
    if request.method == 'POST':
        if form.is_valid():
            dni = form.cleaned_data["dni"]
            sql = "SELECT * FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
            cursor.execute(sql)
            
            consulta = cursor.fetchone()
            if consulta is not None:    
                contrato = []
                sql = "SELECT * FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
                cursor.execute(sql)
                contrato = [ {'dni':fila[0], 'nombre':fila[1], 'apellidos':fila[2], 'fecha_nacimiento':fila[3], 'telefono':fila[4], 'cuenta_bancaria':fila[5], 'sueldo':fila[6], 'duracion_contrato':fila[7]} for fila in  cursor.fetchall()]
                return render(request,"mostrar_contrato.html", {"contrato": contrato})     
            else:
                messages.error(request, '[ERROR] No existe un contrato con el DNI ingresado')
                return render(request,"consultar_contrato.html", {"form": form})

    return render(request, 'consultar_contrato.html',{'form':form})

def modificar_contrato(request):
    form = ModificaForm(request.POST)
    
    cursor = bd.ConnectionBD().get_conexion().cursor()
    if request.method == 'POST':
        if form.is_valid():
            dni = form.cleaned_data["dni"]
            nombre = form.cleaned_data["nombre"]
            apellidos = form.cleaned_data["apellidos"]
            fecha_nacimiento = form.cleaned_data["fecha_nacimiento"]
            telefono = form.cleaned_data["telefono"]
            sueldo = form.cleaned_data["sueldo"]
            cuenta_bancaria = form.cleaned_data["cuenta_bancaria"]
            duracion_contrato = form.cleaned_data["duracion_contrato"] 

            try:
                sql = "SELECT * FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
                cursor.execute(sql)
                consulta = cursor.fetchone()

                if consulta is not None:    
                    sql = "UPDATE CONTRATO SET NOMBRE='{1}', APELLIDOS='{2}',FECHA_NACIM=TO_DATE('{3}','YYYY-DD-MM'),TELEFONO='{4}',SUELDO='{5}',CUENTABANCARIA='{6}',DURACION='{7}' WHERE DNI = '{0}'".format(str(dni), str(nombre), str(apellidos), str(fecha_nacimiento), str(telefono), str(sueldo), str(cuenta_bancaria), str(duracion_contrato))
                    cursor.execute(sql)
                    bd.ConnectionBD().get_conexion().commit()
                    messages.success(request, '[INFO] Contrato modificado correctamente')
                else:
                    messages.error(request, '[ERROR] No existe un contrato con el ID ingresado')
                    return render(request,"modificar_contrato.html", {"form": form})
            except:
                messages.error(request, '[ERROR] Fallo al modificar el contrato')
                return render(request,"modificar_contrato.html", {"form": form})
    
    return render(request, 'modificar_contrato.html',{'form':form})

Ghandi/rh/templates/agendar_entrevista.html
{% extends 'base.html'%}

{% block content %}
<h2>Agendar Entrevista</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Agendar Entrevista</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'rh:menu_rh' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/rh/templates/alta_contrato.html
{% extends 'base.html'%}

{% block content %}
<h2>Nuevo Contrato</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Añadir Contrato</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'rh:menu_rh' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/rh/templates/baja_contrato.html
{% extends 'base.html'%}

{% block content %}
<h2>Eliminar Contrato</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Borrar Contrato</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'rh:menu_rh' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/rh/templates/base.html
<!DOCTYPE html>   
<html>   
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<title> Veterinaria Ghandi</title>  
<center><h1> Veterinaria Ghandi</h1><center>
</head>    
<body class="bg-light" >    
    
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        {{ message }}
      </div>
    {% endfor %}

    {% block content %}
    <center>
        <a class="btn btn-primary" href="login" role="button">Iniciar sesión en la BD</a>
    </center>
    {% endblock content %}

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>     
</html> 

Ghandi/rh/templates/consultar_contrato.html
{% extends 'base.html'%}

{% block content %}
<h2>Consultar Contrato</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Consultar Contrato</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'rh:menu_rh' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/rh/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <center> <h1> Establecimiento de conexión a la Base de Datos de Oracle </h1> </center>   
    <form method="post">  
        {% csrf_token %}
        <div class="container">
            {{ form }}
            <button type="submit">Login</button>   
        </div>
        {% if error_message %}
        <br>
        <div class="alert alert-danger">
            <center>{{ error_message }}</div></center>
        </div>
        {% endif %}
    </form>     

{% endblock content %}  

Ghandi/rh/templates/menu_rh.html
{% extends 'base.html' %}

{% block content%}
    <div style="center;"> 
        <form method="post">  
            {% csrf_token %}
        <div>
        <button class="btn btn-primary" id="alta_contrato-btn" name="alta_contrato-btn" type="submit">
            Dar de alta un contrato
        </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="baja_contrato-btn" name="baja_contrato-btn" type="submit">
                Dar de baja un contrato
            </button>
            </div>
            <br>
            <div>
            <button class="btn btn-primary" id="agendar_entrevista-btn" name="agendar_entrevista-btn" type="submit">
                Agendar una entrevista
            </button>
            </div>
            <br>
            <div>
                <button class="btn btn-primary" id="consultar_contrato-btn" name="consultar_contrato-btn" type="submit">
                    Consultar un contrato
                </button>
                </div>

                <br>
                <div>
                    <button class="btn btn-primary" id="modificar_contrato-btn" name="modificar_contrato-btn" type="submit">
                        Modificar un contrato
                    </button>
                    </div>
        </form> 
        <br>
        
        <center>
            <div>
                <a href="{% url 'login:menu' %}" class="btn btn-secondary" id="volver-menu-btn">Volver atrás</a>
            </div>
            </center>
        
    </div>

{% endblock %}

Ghandi/rh/templates/modificar_contrato.html
{% extends 'base.html'%}

{% block content %}
<h2>Modificar Contrato</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Modificar Contrato</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'rh:menu_rh' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/rh/templates/mostrar_contrato.html
{%extends 'base.html'%}

{% block content %}

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="dni">DNI</th>
        <th scope="nombre">Nombre</th>
        <th scope="apellidos">Apellidos</th>
        <th scope="fecha_nacimiento">Fecha nacimiento</th>
        <th scope="telefono">Teléfono</th>
        <th scope="cuenta_bancaria">Cuenta bancaria</th>
        <th scope="sueldo">Sueldo</th>
        <th scope="duracion_contrato">Duración contrato</th>
      </tr>
    </thead>
    <tbody>
      {% for contrat in contrato %}
        <tr>
          <td>{{ contrat.dni }}</td>
          <td>{{ contrat.nombre }}</td>
          <td>{{ contrat.apellidos }}</td>
          <td>{{ contrat.fecha_nacimiento }}</td>
          <td>{{ contrat.telefono }}</td>
          <td>{{ contrat.cuenta_bancaria }}</td>
          <td>{{ contrat.sueldo }}</td>
          <td>{{ contrat.duracion_contrato }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
<center>
    <a class="btn btn-primary" href="{% url 'rh:menu_rh' %}" role="button">Volver al menú</a>
</center>
{% endblock%}