Ghandi/Ghandi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include(('contabilidad.urls','contabilidad') ,namespace='contabilidad')),
    path('menu/', include(('clientes.urls', 'clientes'), namespace=   'clientes')),
    path('menu/', include(('animales.urls', 'animales'), namespace='animales')),
    path('menu/', include(('logistica.urls', 'logistica'), namespace='logistica')),
    path('menu/', include(('rh.urls', 'rh'), namespace='rh'))
]

Ghandi/clientes/urls.py
from django.urls import path, include
from . import views
app_name = 'clientes'
urlpatterns = [
    path('clientes/', views.menu_cliente, name='menu_clientes'),
    path('clientes/alta', views.alta_cliente, name='alta_cliente'),
    
    path('clientes/view', views.mostrar_clientes, name='mostrar_clientes'),
    path('clientes/viewdates', views.mostrar_citas, name='mostrar_citas'),
    path('clientes/search', views.buscar_clientes, name='buscar_clientes'),
    path('clientes/searchdate', views.buscar_fecha, name='buscar_fecha'),
    path('clientes/searchdate/confirm/<str:pk>', views.confirmar_liberacion_cita, name="confirmar_liberacion"),
    path('clientes/searchdate/reserve/<str:pk>', views.reservar_cita, name="reservar_cita"),
    path('clientes/searchdate/reserve/client/<str:pk>_<str:fecha>', views.asignar_cliente, name="asignar_cliente"),

    path('clientes/search/confirm/<str:pk>', views.confirmar_borrado_cliente, name="confirmar_borrado"),
    path('clientes/search/modify/<str:pk>', views.modificar_cliente, name='modificar_cliente'),
]

Ghandi/login/urls.py
from django.urls import path, include
from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index_login'),
    path('login/', views.login, name='login'),
    path('menu/', views.menu, name="menu"),
    path('logout/',views.logout, name="logout")
]

Ghandi/rh/urls.py
from django.urls import path, include
from . import views
app_name = 'rh'
urlpatterns = [
    path('rh/', views.menu_rh, name='menu_rh'),
    path('rh/alta_contrato', views.alta_contrato, name='alta_contrato'),
    path('rh/baja_contrato', views.baja_contrato, name='baja_contrato'),
    path('rh/agendar_entrevista', views.agendar_entrevista, name='agendar_entrevista'),
    path('rh/consultar_contrato', views.consultar_contrato, name='consultar_contrato'),
    path('rh/modificar_contrato', views.modificar_contrato, name='modificar_contrato')
]

Ghandi/clientes/models.py
from django.db import models

# Create your models here.

Ghandi/clientes/forms.py
from django import forms
from bootstrap_datepicker_plus.widgets import DatePickerInput


class NuevoClienteForm(forms.Form):
   nombre = forms.CharField(
                  label="Nombre",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce nombre del cliente"}))
   apellidos = forms.CharField(
                  label="Apellidos",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce apellidos del cliente"}))
   telefono = forms.CharField(label="Telefono",widget=forms.TextInput(attrs={'placeholder': "Introduce telefono del cliente"}), required=False)
   direccion = forms.CharField(label="Direccion",widget=forms.TextInput(attrs={'placeholder': "Introduce direccion del cliente"}), required=False)
   dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del cliente"}))
   cuenta_banco = forms.CharField(label="Cuenta Banco",widget=forms.TextInput(attrs={'placeholder': "Introduce cuenta del banco del cliente"}), required=False)

class ModificarClienteForm(forms.Form):
   nombre = forms.CharField(
                  label="Nombre",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce nombre del cliente"}))
   apellidos = forms.CharField(
                  label="Apellidos",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce apellidos del cliente"}))
   telefono = forms.CharField(label="Telefono",widget=forms.TextInput(attrs={'placeholder': "Introduce telefono del cliente"}), required=False)
   direccion = forms.CharField(label="Direccion",widget=forms.TextInput(attrs={'placeholder': "Introduce direccion del cliente"}), required=False)
   cuenta_banco = forms.CharField(label="Cuenta Banco",widget=forms.TextInput(attrs={'placeholder': "Introduce cuenta del banco del cliente"}), required=False)


class BuscarClienteForm(  forms.Form):
   nombre = forms.CharField(
                  label="Nombre",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce nombre del cliente"}), required=False)
   apellidos = forms.CharField(
                  label="Apellidos",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce apellidos del cliente"}), required=False)
   dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del cliente"}), required=False)


class BuscarFechaForm(forms.Form):
   date = forms.DateField(widget = DatePickerInput())

            
   

Ghandi/clientes/views.py
#from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from login import bd 
from .forms import NuevoClienteForm, BuscarClienteForm, BuscarFechaForm, ModificarClienteForm
from .tables import ClienteTabla, ClienteTablaCompleta, Horas
from datetime import datetime
from django.urls import reverse
busqueda_cliente =""
clientes_g = ""
def main_cliente(request):
    return render(request, "main_cliente.html")

def mostrar_clientes(request):

    cursor = bd.ConnectionBD().get_conexion().cursor()
    clientes = [] 
    cursor.execute("SELECT dni, nombre, apellidos, telefono FROM cliente")
    
    clientes = [ {'dni':fila[0], 'nombre':fila[1], 'apellido':fila[2], 'telefono':fila[3]} for fila in  cursor.fetchall()]
    return render(request,"mostrar_clientes.html", {"clientes": clientes})

def mostrar_citas(request):

    cursor = bd.ConnectionBD().get_conexion().cursor()
    clientes = [] 
    cursor.execute("SELECT fechahora, cita.dni, nombre, apellidos FROM cita LEFT JOIN cliente on cita.dni = cliente.dni")
    
    citas = [ {'fecha':fila[0],'dni':fila[1], 'nombre':fila[2], 'apellido':fila[3]} for fila in  cursor.fetchall()]

    return render(request,"mostrar_citas.html", {"citas": citas})


def buscar_clientes(request):
    if request.method == 'POST':
        
        form = BuscarClienteForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data["nombre"]
            apellidos = form.cleaned_data["apellidos"]
            dni = form.cleaned_data["dni"]
            
            
            try:
                clientes = [] 
                if (dni != ""):
                    print("Buscando cliente: ", dni)
                    
                    
                    sql = "SELECT dni, nombre, apellidos, telefono, direccion, cuentabancaria FROM cliente WHERE dni = '{0}'".format(str(dni))
                    
                    if (nombre != ""):
                        sql +="AND nombre = '{0}'".format(str(nombre))
                    if (apellidos != ""):
                        sql +="AND apellidos = '{0}'".format(str(apellidos))
                    print(sql)
                else:
                    sql = "SELECT dni, nombre, apellidos, telefono, direccion, cuentabancaria FROM cliente"
                    
                    if (nombre !="" or apellidos != ""):
                        sql += " WHERE"
                        if (nombre != ""):
                            sql +=" nombre = '{0}'".format(str(nombre))
                            if (apellidos != ""):
                                sql +=" AND apellidos = '{0}'".format(str(apellidos))
                        else:
                            sql +=" apellidos = '{0}'".format(str(apellidos))  
                    print(sql)


                cursor = bd.ConnectionBD().get_conexion().cursor()
                cursor.execute(sql)
                print(sql)
                clientes = [ {'dni':fila[0], 'nombre':fila[1], 'apellido':fila[2], 'telefono':fila[3], 'direccion':fila[4], 'cuenta':fila[5]} for fila in  cursor.fetchall()]
                print(clientes)
                
                return render(request,"buscar_clientes.html", {"form":form , "clientes": clientes})
            except:
                error_message="ERROR: Datos del cliente incorrectos"
                return render(request,"buscar_clientes.html", {"form": form, "error_message": error_message})
    return render(request, "buscar_clientes.html", {"form": BuscarClienteForm(), "clientes":[]})


def buscar_fecha(request):
    if request.method == 'POST':
        
        form = BuscarFechaForm(request.POST)
        if form.is_valid():
            fecha = form.cleaned_data["date"].strftime("%d/%m/%y")
            
            try:
                print("Buscando fecha: ", fecha)
                cursor = bd.ConnectionBD().get_conexion().cursor()
                horas = [] 

                sql = "SELECT fechahora FROM cita WHERE disponibilidad = 'Y' AND TO_CHAR(fechahora, 'DD/MM/YY' ) LIKE '{0}'".format(str(fecha))
                print(sql)
                
                cursor.execute(sql)
                
                horas = [ {'fecha':fila[0],'hora':fila[0].strftime("%H:%M")} for fila in  cursor.fetchall()]
                if (len(horas) == 0):
                    error_message="ERROR: No hay citas disponibles para la fecha seleccionada"
                    return render(request,"buscar_fecha.html", {"form": form, "error_message": error_message})
                return render(request,"buscar_fecha.html", {"form":form , "horas": horas})
            except:
                error_message="ERROR: Datos de fecha incorrectos"
                return render(request,"buscar_fecha.html", {"form": form, "error_message": error_message})
    return render(request, "buscar_fecha.html", {"form": BuscarFechaForm(), "horas":[]})


def alta_cliente(request):
    if request.method == 'POST':
        form = NuevoClienteForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data["nombre"]
            apellidos = form.cleaned_data["apellidos"]
            direccion = form.cleaned_data["direccion"]
            telefono = form.cleaned_data["telefono"]
            dni = form.cleaned_data["dni"]
            cuenta_bancaria = form.cleaned_data["cuenta_banco"]
            try:
                
                print("Dando de alta cliente: ", nombre, apellidos)
                cursor = bd.ConnectionBD().get_conexion().cursor()
                sql = "INSERT INTO cliente(dni, nombre, apellidos, telefono) VALUES ('{0}', '{1}', '{2}', '{3}')".format(str(dni),str(nombre).upper(), str(apellidos).upper(), str(telefono))
                cursor.execute(sql)
                bd.ConnectionBD().get_conexion().commit()
                print(sql)
                messages.success(request, 'Cliente añadido correctamente')
                
                return redirect("clientes:alta_cliente")
            except:
                messages.error(request, 'Error al añadir el cliente: ese DNI no es válido')
                error_message="ERROR: Datos del cliente incorrectos"
                return render(request,"alta_cliente.html", {"form": form, "error_message": error_message})

    return render(request, "alta_cliente.html", {"form": NuevoClienteForm()})
    

def modificar_cliente(request, pk):
    if request.method == 'POST':
        form = ModificarClienteForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            nombre = form.cleaned_data["nombre"]
            apellidos = form.cleaned_data["apellidos"]
            direccion = form.cleaned_data["direccion"]
            telefono = form.cleaned_data["telefono"]
            cuenta_bancaria = form.cleaned_data["cuenta_banco"]
                
            print("Modificando cliente: ", nombre, apellidos)
            cursor = bd.ConnectionBD().get_conexion().cursor()
            try:
                sql = "UPDATE cliente SET "
                if (nombre != '') :sql += "nombre='{0}'".format(str(nombre).upper())
                if (apellidos != '') :sql += ", apellidos='{0}'".format(str(apellidos).upper())
                if (direccion != '') :sql += ", direccion='{0}'".format(str(direccion).upper())
                if (telefono != '') :sql += ", telefono='{0}'".format(str(telefono))
                if (cuenta_bancaria != '') :sql += ", cuentabancaria='{0}'".format(str(cuenta_bancaria))
                sql += "WHERE dni='{0}'".format( str(pk))
                print(sql)

                cursor.execute(sql)
                bd.ConnectionBD().get_conexion().commit()
                
                messages.success(request, 'Cliente modificado correctamente')
            except:
                messages.error(request, 'Error al modificar el cliente, datos no válidos')
                error_message="ERROR: Datos del cliente incorrectos. Pruebe a dar de alta un nuevo cliente"
                return render(request,"alta_cliente.html", {"form": form, "error_message": error_message})

            # si se ha conectado bien a la BD, lo redireccionamos  a la url del menú principal de la aplicación
            return redirect("clientes:mostrar_clientes")
            
    valores_iniciales = {'dni':pk}
    
    sql = "SELECT dni, nombre, apellidos, telefono, direccion, cuentabancaria FROM cliente WHERE dni = '{0}'".format(str(pk))
    try:
        cursor = bd.ConnectionBD().get_conexion().cursor()
        cursor.execute(sql)
        cliente = cursor.fetchall()[0]
        if (cliente[1]!=''): valores_iniciales['nombre']=cliente[1]
        if (cliente[2]!=''): valores_iniciales['apellidos']=cliente[2]
        if (cliente[3]!=''): valores_iniciales['telefono']=cliente[3]
        if (cliente[4]!=''): valores_iniciales['direccion']=cliente[4]

        if (cliente[5]!=''): valores_iniciales['cuenta_banco']=cliente[5]

        form = ModificarClienteForm(initial=valores_iniciales)
        return render(request, "modificar_cliente.html", {"form": form, "dni": pk})
    except:
        form = ModificarClienteForm()
        error_message="ERROR: No se han podido cargar los datos iniciales"
        return render(request,"modificar_cliente.html", {"form": form, "dni": pk, "error_message": error_message})
    
            
def confirmar_borrado_cliente(request, pk):
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
        
        if 'borrar-btn' in keys_request_POST:
            print("aqui")
            try:
                print("Borrando cliente: ", pk)
                cursor = bd.ConnectionBD().get_conexion().cursor()

                sql = "DELETE FROM CLIENTE WHERE DNI LIKE '{0}'".format(str(pk))
                print(sql)
                
                cursor.execute(sql)
                bd.ConnectionBD().get_conexion().commit()

Ghandi/clientes/templates/addcliente.html
{% extends 'base.html'%}

{% block content %}
<h2>Nuevo Cliente</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Añadir Cliente</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'menu' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/clientes/templates/alta_cliente.html
{% extends 'baseclientes.html'%}

{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}
<br>
<center>
<h3>Dar de alta cliente</h3>
<br>



<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Añadir Cliente</button>
</form>
</center>
<br>
<center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/clientes/templates/buscar_clientes.html
{%extends 'base.html'%}
{% load render_table from django_tables2 %}

{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Clientes</h2> </center>
<br>

<h3>Buscar Clientes</h3>

<form method="POST" class="post-form" >
  {% csrf_token %}
  {{ form.as_p  }}
  <br>
  <br>
  <button type="submit" class="btn btn-primary">Buscar clientes</button>
</form>
<br>
<br>

{% if error_message %}
        <br>
        <div class="alert alert-danger">
            <center>{{ error_message }}</div></center>
        </div>
        {% endif %}


<br>
<br>

<table class="table table-striped" style="width:600px">
    <thead>
      <tr>
        <th scope="dni">DNI</th>
        <th scope="nombre">Nombre</th>
        <th scope="apellido">Apellido</th>
        <th scope="telefono">Teléfono</th>
        <th scope="direccion">Dirección</th>
        <th scope="cuenta">Cuenta Bancaria</th>
        <th scope="action">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in clientes %}
        <tr class ='clickableRow'>
          <td>{{ cliente.dni }}</td>
          <td>{{ cliente.nombre }}</td>
          <td>{{ cliente.apellido }}</td>
          <td>{{ cliente.telefono }}</td>
          
          <td>{{ cliente.direccion }}</td>
          <td>{{ cliente.cuenta }}</td>
          <td><a href="{% url 'clientes:confirmar_borrado' pk=cliente.dni %}">
            <button type="button" class="btn btn-danger">Delete</button>
          </a> <br> <a href="{% url 'clientes:modificar_cliente' pk=cliente.dni %}">
            <button type="button" class="btn btn-success">Modificar</button>
          </a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  <center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 
{% endblock%}

Ghandi/clientes/templates/buscar_fecha.html
{%extends 'baseclientes.html'%}
{% load render_table from django_tables2 %}


{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}


<center><h3>Buscar citas</h3></center>
<div style="width: 200px;
margin: auto;"> 
<form method="POST" class="post-form"  >
  
  {% csrf_token %}
  {{ form.media }}
  {{ form.as_p }}
  <br>
  <br>
  <button type="submit" class="btn btn-primary">Buscar fechas</button>
</form>
</div>
<br>
<br>

{% if error_message %}
        <br>
        <div class="alert alert-danger">
            <center>{{ error_message }}</div></center>
        </div>
        {% endif %}


  
<br>
<br>
<center>
<div style="width: 100"></div>
<table class="table table-striped" style="width:600px">
  <thead>
    <tr>
      <th scope="fecha">Hora</th>
      
    </tr>
  </thead>
  <tbody>
    {% for hora in horas %}
      <tr class ='clickableRow'>
        <td>{{ hora.hora }}</td>
        <td><a href="{% url 'clientes:reservar_cita' pk=hora.fecha%}">
          <button type="button" class="btn btn-primary">Reservar</button>
        </a> </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</center>
  <center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 
{% endblock%}

Ghandi/clientes/templates/confirmacion_borrado.html
{%extends 'baseclientes.html'%}
{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}
<br>

    <center>
    <div style="center;"> 

        <h3>¿Está seguro de que quiere borrar el cliente con DNI: {{dni}}?</h3>
        <form method="post">  
            {% csrf_token %}
        <div>
        <button class="btn btn-primary" id="borrar-btn" name="borrar-btn" type="submit">
            Borrar
        </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="cancelar-btn" name="cancelar-btn" type="submit">
                Cancelar
            </button>
            </div>
            <br>
   
        </form>      
    </div>
</center>

{% endblock %}

Ghandi/clientes/templates/menu_cliente.html
{% extends 'base.html' %}

{% block content%}
<center> <h2>Área de Clientes</h2> </center>

<center> <h5><FONT COLOR=grey>by María Aguado</FONT></h5> </center>
    <div style="center;"> 
        <form method="post">  
            {% csrf_token %}
        <div>
        <button class="btn btn-primary" id="alta-cliente-btn" name="alta-cliente-btn" type="submit">
            Dar de alta nuevo cliente
        </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="mostrar-clientes-btn" name="mostrar-clientes-btn" type="submit">
                Mostrar todos los clientes
            </button>
            </div>
            <br>
            <div>
                <button class="btn btn-primary" id="buscar-clientes-btn" name="buscar-clientes-btn" type="submit">
                    Buscar clientes
                </button>
                </div>

                <br>
                <div>
                    <button class="btn btn-primary" id="buscar-fecha-btn" name="buscar-fecha-btn" type="submit">
                        Buscar horas disponibles
                    </button>
                    </div>
                    <br>
                    <div>
                        <button class="btn btn-primary" id="mostrar-citas-btn" name="mostrar-citas-btn" type="submit">
                            Mostrar Citas
                        </button>
                        </div>
        </form> 
        <br>
        
        <center>
            <div>
                <a href="{% url 'login:menu' %}" class="btn btn-secondary" id="volver-menu-btn">Volver atrás</a>
            </div>
            </center>
        
    </div>

{% endblock %}

Ghandi/clientes/templates/modificar_cliente.html
{% extends 'baseclientes.html'%}

{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}
<br>
<center>
<h3>Modificación cliente</h3>
<h4>DNI: {{dni}}</h4>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Modificar Cliente</button>
</form>

<br>
</center>
<center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/clientes/templates/mostrar_citas.html
{%extends 'baseclientes.html'%}

{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}



<center>
  <h3>Mostrar citas</h3>
<table class="table table-striped" style="width:800px">
    <thead>
      <tr>
        <th scope="fecha">Fecha</th>
        <th scope="dni">DNI</th>
        <th scope="nombre">Nombre</th>
        <th scope="apellido">Apellido</th>
        <th scope="acciones">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for cita in citas %}
        <tr>
          <td>{{ cita.fecha }}</td>
          {% if cita.dni %}
          <td>{{ cita.dni }}</td>
          <td>{{ cita.nombre }}</td>
          <td>{{ cita.apellido }}</td>
          
            <td>
              <div style="display:block;"><nobr>
              <a href="{% url 'clientes:confirmar_liberacion' pk=cita.fecha %}">
              <button type="button" class="btn btn-success">Liberar</button>
            </a>     <a href="{% url 'clientes:reservar_cita' pk=cita.fecha %}">
              <button type="button" class="btn btn-warning">Modificar Cliente</button>
            </a></nobr></div>
          </td>
        {% endif %}
        {% if not cita.dni %}
        <td> </td>
        <td> </td>
        <td> </td>
        
          <td><a href="{% url 'clientes:reservar_cita' pk=cita.fecha %}">
            <button type="button" class="btn btn-primary">Reservar</button>
          </a></td>
      {% endif %}
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
</center>
  <center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 
{% endblock%}

Ghandi/clientes/templates/mostrar_clientes.html
{%extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Clientes</h2> </center>
<br>

<h3>Mostrar clientes</h3>
<div style="width: 100"></div>
<table class="table table-bordered" style="width:600px">
    <thead>
      <tr>
        <th scope="dni">DNI</th>
        <th scope="nombre">Nombre</th>
        <th scope="apellido">Apellido</th>
        <th scope="telefono">Teléfono</th>
        <th scope="action">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in clientes %}
        <tr>
          <td>{{ cliente.dni }}</td>
          <td>{{ cliente.nombre }}</td>
          <td>{{ cliente.apellido }}</td>
          <td>{{ cliente.telefono }}</td>
          <td><a href="{% url 'clientes:confirmar_borrado' pk=cliente.dni %}">
            <button type="button" class="btn btn-danger">Delete</button>
          </a>
          <a href="{% url 'clientes:modificar_cliente' pk=cliente.dni %}">
            <button type="button" class="btn btn-success">Modificar</button>
          </a>
        </td>

          
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  <center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 
{% endblock%}

Ghandi/clientes/templates/reserva_cita.html
{%extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Clientes</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Clientes</h2> </center>
<br>

<h3>Reservar cita</h3>
<h4>Seleccione el cliente para la cita {{fecha}} </h4>
<div style="width: 100"></div>
<table class="table table-bordered" style="width:600px">
    <thead>
      <tr>
        <th scope="dni">DNI</th>
        <th scope="nombre">Nombre</th>
        <th scope="apellido">Apellido</th>
        <th scope="telefono">Teléfono</th>
        <th scope="action">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in clientes %}
        <tr>
          <td>{{ cliente.dni }}</td>
          <td>{{ cliente.nombre }}</td>
          <td>{{ cliente.apellido }}</td>
          <td>{{ cliente.telefono }}</td>
          <td><a href="{% url 'clientes:asignar_cliente' pk=cliente.dni fecha=fecha %}">
            <button type="button" class="btn btn-primary">Reservar</button>

          </a>
        </td>

          
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  <center>
    <a class="btn btn-primary" href="{% url 'clientes:menu_clientes' %}" role="button">Volver al menú</a>
</center> 
{% endblock%}