Ghandi/Ghandi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include(('contabilidad.urls','contabilidad') ,namespace='contabilidad')),
    path('menu/', include(('clientes.urls', 'clientes'), namespace=   'clientes')),
    path('menu/', include(('animales.urls', 'animales'), namespace='animales')),
    path('menu/', include(('logistica.urls', 'logistica'), namespace='logistica')),
    path('menu/', include(('rh.urls', 'rh'), namespace='rh'))
]

Ghandi/login/urls.py
from django.urls import path, include
from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index_login'),
    path('login/', views.login, name='login'),
    path('menu/', views.menu, name="menu"),
    path('logout/',views.logout, name="logout")
]

Ghandi/logistica/urls.py
from django.urls import path, include
from . import views
app_name = 'logistica'
urlpatterns = [
    #path('menu/', include(('login.urls', 'ghandi'), namespace='rh')),
    path('logistica/', views.menu_logistica, name='menu_logistica'),
    path('logistica/hacer_pedido', views.hacer_pedido, name='hacer_pedido'),
    path('logistica/consultar_stock', views.consultar_stock, name='consultar_stock'),
    path('logistica/almacenar_producto', views.almacenar_producto, name='almacenar_producto'),
    path('logistica/asignar_jaula', views.asignar_jaula, name='asignar_jaula'),
    path('logistica/consultar_disponibilidad_jaulas', views.consultar_disponibilidad_jaulas, name='consultar_disponibilidad_jaulas'),
    path('logistica/vaciar_jaula', views.vaciar_jaula, name='vaciar_jaula'),
    path('logistica/alta_producto_almacen', views.alta_producto_almacen, name='alta_producto_almacen'),
]

Ghandi/rh/urls.py
from django.urls import path, include
from . import views
app_name = 'rh'
urlpatterns = [
    path('rh/', views.menu_rh, name='menu_rh'),
    path('rh/alta_contrato', views.alta_contrato, name='alta_contrato'),
    path('rh/baja_contrato', views.baja_contrato, name='baja_contrato'),
    path('rh/agendar_entrevista', views.agendar_entrevista, name='agendar_entrevista'),
    path('rh/consultar_contrato', views.consultar_contrato, name='consultar_contrato'),
    path('rh/modificar_contrato', views.modificar_contrato, name='modificar_contrato')
]

Ghandi/login/models.py
from django.db import models

# Create your models here.

Ghandi/login/forms.py
from django import forms

class LoginBDForm(forms.Form):
   username = forms.CharField(
                  label="Nombre de Usuario",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce nombre de usuario"}))
   password = forms.CharField(
                  label="Contraseña",
                  widget=forms.TextInput(attrs={'placeholder': "Introduce contraseña"}))

Ghandi/logistica/forms.py
from django import forms

class HacerPedidoForm(forms.Form):
    idpedido = forms.IntegerField(label="idPedido", required=False,widget=forms.TextInput(attrs={'placeholder': "idPedido (Opcional)"}))
    cantidad = forms.CharField(label="Cantidad", widget=forms.TextInput(attrs={'placeholder': "Cantidad"}))
    fecha = forms.DateField(label="Fecha", widget=forms.TextInput(attrs={'placeholder': "Fecha (DD/MM/YYYY)"}))
    pagado = forms.CharField(label="Pagado",required=False, max_length=1, widget=forms.TextInput(attrs={'placeholder': "Pagado (S/N) (Opcional)"}))
    idproducto = forms.CharField(label="idProducto", widget=forms.TextInput(attrs={'placeholder': "idProducto"}))

class StockForm(forms.Form):
    idproducto = forms.IntegerField(label="idProducto", required=False, widget=forms.TextInput(attrs={'placeholder': "idProducto"}))
    nombreproducto = forms.CharField(label="Nombre Producto", required=False, widget=forms.TextInput(attrs={'placeholder': "Nombre"}))

class DisponibilidadForm(forms.Form):
    idjaula = forms.IntegerField(label="idJaula", required=False, widget=forms.TextInput(attrs={'placeholder': "idJaula"}))
    
class AsignarForm(forms.Form):
    idjaula = forms.IntegerField(label="idJaula", widget=forms.TextInput(attrs={'placeholder': "idJaula"}))
    idanimal = forms.IntegerField(label="idAnimal", widget=forms.TextInput(attrs={'placeholder': "idAnimal"}))

class AlmacenarForm(forms.Form):
    idproducto = forms.IntegerField(label="idProducto", widget=forms.TextInput(attrs={'placeholder': "idProducto"}))
    cantidad = forms.CharField(label="Cantidad", widget=forms.TextInput(attrs={'placeholder': "Cantidad"}))

class AltaProductoForm(forms.Form):
    idproducto = forms.IntegerField(label="idProducto", required=False, widget=forms.TextInput(attrs={'placeholder': "idProducto (Opcional)"}))
    nombreproducto = forms.CharField(label="Nombre Producto", widget=forms.TextInput(attrs={'placeholder': "Nombre"}))

Ghandi/login/views.py
#from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
import datetime
from datetime import datetime as dt
from datetime import timedelta
from .forms import LoginBDForm

from . import bd

import cx_Oracle
#bd = 0

def index(request):
    return render(request, "base.html")

def login(request):
    if request.method == 'POST':
        form = LoginBDForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            try:
                #global bd # para poder usar la variable global, ha de invocarse
                bd.ConnectionBD().establecer_conexion(username, password)
                print("EStableciendo conexion: ", username, password)
                # si se ha conectado bien a la BD, lo redireccionamos  a la url del menú principal de la aplicación
                return redirect("login:menu")
            except:
                 error_message="ERROR: Credenciales de usuario y contraseña incorrectas para la conexión a la base de datos de Oracle"
                 return render(request,"login.html", {"form": form, "error_message": error_message})

    # si no se ha hecho un post o hay errores en los campos del form, se presenta de nuevo el formulario vacío para rellenarlo
    return render(request,"login.html", {"form": LoginBDForm()})



    
    



def menu(request):
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
            # Obtengo las claves del diccionario request.POST, que por ejemplo tiene el valor:
            # <QueryDict: {'csrfmiddlewaretoken': ['CHNZtCiLbU'], 'alamcen-btn': ['']}> 
            # Me quedo con las claves para coger "almacen-btn", que es la que me interesa 
            # coger (según el boton que pulse y se escoja hacer una acción u otra)
        if 'clientes-btn' in keys_request_POST:
            return HttpResponseRedirect("clientes")
        elif 'contabilidad-btn' in keys_request_POST:
            return HttpResponseRedirect("contabilidad")
        elif 'logistica-btn' in keys_request_POST:
            return HttpResponseRedirect("logistica")
        elif 'animales-btn' in keys_request_POST:
            return HttpResponseRedirect("animales")
        elif 'rh-btn' in keys_request_POST:
            return HttpResponseRedirect("rh")
        elif 'cerrar-btn' in keys_request_POST:
            return logout(request)
    return render(request, 'menu.html')



def logout(request):
    bd.ConnectionBD().cerrar_conexion()
    return HttpResponseRedirect("/")

Ghandi/logistica/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import HacerPedidoForm, StockForm, AlmacenarForm, DisponibilidadForm, AsignarForm, AltaProductoForm
from django.contrib import messages
from login import bd

import cx_Oracle

def index(request):
    return HttpResponse("Hello, World!")

def menu_logistica(request):
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
        if 'hacerpedido-btn' in keys_request_POST:
            return redirect("logistica:hacer_pedido")
        elif 'consultarstock-btn' in keys_request_POST:
            return redirect("logistica:consultar_stock")
        elif 'almacenarproducto-btn' in keys_request_POST:
            return redirect("logistica:almacenar_producto")
        elif 'asignarjaula-btn' in keys_request_POST:
            return redirect("logistica:asignar_jaula")
        elif 'consultardisponibilidadjaulas-btn' in keys_request_POST:
            return redirect("logistica:consultar_disponibilidad_jaulas")
        elif 'vaciarjaula-btn' in keys_request_POST:
            return redirect("logistica:vaciar_jaula")
        elif 'altaproductoalmacen-btn' in keys_request_POST:
            return redirect("logistica:alta_producto_almacen")
    return render(request, 'menu_logistica.html')

def logout(request):
    return HttpResponseRedirect("/menu")

def hacer_pedido(request):
    #form = HacerPedidoForm()
    if request.method == 'POST':
        form = HacerPedidoForm(request.POST)
        if form.is_valid():
            idpedido = form.cleaned_data["idpedido"]
            cantidad = form.cleaned_data["cantidad"]
            fecha = form.cleaned_data["fecha"]
            pagado = form.cleaned_data["pagado"]
            idproducto = form.cleaned_data["idproducto"]
            print(cantidad)
            if (',' not in str(cantidad) and '.' not in str(cantidad)):
                cantidad = str(cantidad) + '.0'  
            print(cantidad)          
            if ',' in str(cantidad):
                cant_split = (str(cantidad)).split(',')
                cantidad = cant_split[0] + '.' + cant_split[1]
            print(cantidad)
            try:
                a = float(str(cantidad))
            except:
                error_message="ERROR: Cantidad en Formato Incorrecto"
                return render(request,"hacerpedido.html", {"form": form, "error_message": error_message})
        
            print(fecha)
            cantidad_split = str(fecha).split('-')
            if len(cantidad_split) != 3 or len(cantidad_split[0]) != 4 or len(cantidad_split[1]) != 2 or len(cantidad_split[2]) != 2:
                error_message="ERROR: Fecha en Formato Incorrecto"
                return render(request,"hacerpedido.html", {"form": form, "error_message": error_message})
            print(str(pagado))
            if (str(pagado) not in ['S','N']) and str(pagado) != '' and str(pagado) != 'None':
                error_message="ERROR: El atributo Pagado debe ser 'S' (sí) o 'N' (no)"
                return render(request,"hacerpedido.html", {"form": form, "error_message": error_message})
            elif (pagado == 'None' or pagado == ''):
                pagado = 'N'

            try:
                cursor = bd.ConnectionBD().get_conexion().cursor()
                
                if str(idpedido) == 'None':
                    sql = "SELECT idpedido FROM pedido"
                    cursor.execute(sql)
                    print("cursor funciona2")
                    pedidos = []
                    pedidos = [ {'idpedido':fila[0]} for fila in  cursor.fetchall()]
                    ids = []
                    for pedido in pedidos:
                        ids.append(int(pedido['idpedido']))
                    print(ids)
                    ids.sort(reverse=True)
                    print(ids)
                    idpedido = ids[0]+1
                else:
                    sql = "SELECT idpedido FROM pedido WHERE idpedido={0}".format(str(idpedido))
                    cursor.execute(sql)
                    print("cursor funciona2")
                    pedidos = []
                    pedidos = [ {'idpedido':fila[0]} for fila in  cursor.fetchall()]

                    if pedidos != []:
                        error_message="ERROR: Ya existe un Pedido con ese idPedido"
                        return render(request,"hacerpedido.html", {"form": form, "error_message": error_message})
                
                sql = "SELECT idproducto FROM producto WHERE idproducto={0}".format(str(idproducto))
                cursor.execute(sql)
                print("cursor funciona2")
                productos = []
                productos = [ {'idproducto':fila[0]} for fila in  cursor.fetchall()]

                if productos == []:
                    error_message="ERROR: Ese Producto no está registrado, debes darlo de alta primero"
                    return render(request,"hacerpedido.html", {"form": form, "error_message": error_message})
            
                print("cursor funciona4")
                sql = "INSERT INTO PEDIDO VALUES ({0}, {1}, TO_DATE('{2}','YYYY-DD-MM'), '{3}', {4})".format(str(idpedido), str(cantidad), str(fecha), str(pagado), str(idproducto)) 
                print(sql)
                cursor = bd.ConnectionBD().get_conexion().cursor()
                cursor.execute(sql)

                print("llego casi commit")
                bd.ConnectionBD().get_conexion().commit()
                
                messages.success(request, '    Pedido Realizado con Éxito')
                
                return redirect("logistica:hacer_pedido")
            except:
                error_message="ERROR: El SGBD no ha aceptado la operación"
                return render(request,"hacerpedido.html", {"form": form, "error_message": error_message})
        else:
            error_message="[ERROR] Fallo en los datos introducidos"
            return render(request,"hacerpedido.html",{'form':form, 'error_message':error_message})
    return render(request,"hacerpedido.html", {"form": HacerPedidoForm()})

def consultar_stock(request):
    #form = StockForm()
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
        if 'consulta1' in keys_request_POST:
            form = StockForm(request.POST)
            if form.is_valid():
                idproducto = form.cleaned_data["idproducto"]
                nombreproducto = form.cleaned_data["nombreproducto"]

                cursor = bd.ConnectionBD().get_conexion().cursor()
                sql = "SELECT * FROM Producto WHERE idproducto='{0}' OR nombre='{1}'".format(str(idproducto),str(nombreproducto).upper())
                print(sql)
                cursor.execute(sql)
                productos = []
                productos = [ {'idproducto':fila[0], 'nombre':fila[1], 'cantidad':fila[2]} for fila in  cursor.fetchall()]
                if productos == []:
                    error_message="ERROR: El Producto no existe"
                    return render(request,"consultarstock.html", {"form": StockForm, "error_message": error_message})
                
                return render(request,'consultarstock.html', {"form": StockForm(), "productos": productos})
            else:
                error_message="[ERROR] Fallo en los datos introducidos"
                return render(request,"hacerpedido.html",{'form':form, 'error_message':error_message})
        elif 'consulta2' in keys_request_POST:
            cursor = bd.ConnectionBD().get_conexion().cursor()
            sql = "SELECT * FROM Producto"
            print(sql)
            cursor.execute(sql)
            productos = []
            productos = [ {'idproducto':fila[0], 'nombre':fila[1], 'cantidad':fila[2]} for fila in  cursor.fetchall()]
            
            return render(request,'consultarstock.html', {"form": StockForm(), "productos": productos})
        
    return render(request,"consultarstock.html", {"form": StockForm()})

def almacenar_producto(request):
    if request.method == 'POST':
        form = AlmacenarForm(request.POST)
        if form.is_valid():
            idproducto = form.cleaned_data["idproducto"]
            cantidad = form.cleaned_data["cantidad"]

            if (',' not in str(cantidad) and '.' not in str(cantidad)):
                cantidad = str(cantidad) + '.0'            
            if ',' in str(cantidad):
                cant_split = str(cantidad).split(',')
                cantidad = cant_split[0] + '.' + cant_split[1]

            try:
                cursor = bd.ConnectionBD().get_conexion().cursor()
                print("cursor funciona")
                sql = "SELECT cantidad FROM producto WHERE idproducto='{0}'".format(str(idproducto))
                cursor.execute(sql)
                print("cursor funciona2")
                productos = []
                productos = [ {'cantidad':fila[0]} for fila in  cursor.fetchall()]
                
                print("cursor funciona3")
                if productos == []:
                    error_message="ERROR: El Producto no existe"
                    return render(request,"almacenarproducto.html", {"form": AlmacenarForm, "error_message": error_message})
                print("cursor funciona4")
                old_cantidad = str(productos[0]['cantidad'])
                print(old_cantidad)
                print(cantidad)
                print(old_cantidad + '+' + str(cantidad))
                sql = "UPDATE producto SET cantidad = {0}+{1} WHERE idproducto={2}".format(str(old_cantidad), str(cantidad), str(idproducto))
                print(sql)
                cursor = bd.ConnectionBD().get_conexion().cursor()
                cursor.execute(sql)

                print("llego casi commit")
                bd.ConnectionBD().get_conexion().commit()
                
                messages.success(request, '    Producto Almacenado con Éxito')
                

Ghandi/logistica/templates/addcliente.html
{% extends 'base.html'%}

{% block content %}
<h2>Nuevo Cliente</h2>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Añadir Cliente</button>
</form>

<br>
<center>
    <a class="btn btn-primary" href="{% url 'menu' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/logistica/templates/almacenarproducto.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Almacenar Producto</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Almacenar Producto recibido</button>
</form>

<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al Menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}

Ghandi/logistica/templates/altaproducto.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Alta Producto en Almacén</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Dar de Alta el Nuevo Producto</button>
</form>

<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al Menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}

Ghandi/logistica/templates/asignarjaula.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Asignar Jaula</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Asignar Jaula a Animal</button>
</form>

<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al Menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}

Ghandi/logistica/templates/base.html
<!DOCTYPE html>   
<html>   
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<title>Veterinaria Ghandi - Logistica</title>  
<center><h1>Veterinaria Ghandi</h1><h2>Área de Logística</h2></center> 
</head>    
<body class="bg-light" >    
    
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        {{ message }}
      </div>
    {% endfor %}

    {% block content %}
    <center>
        <a class="btn btn-primary" href="login" role="button">Iniciar sesión en la BD</a>
    </center>
    {% endblock content %}

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>     
</html> 

Ghandi/logistica/templates/consultardisponibilidadjaulas.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Consultar Disponibilidad Jaulas</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form  }}
    <br>
    <br>
    <button id="consulta1" name="consulta1" type="submit">Consultar Jaula</button>
    <br>
    <br>
    <button id="consulta2" name="consulta2" type="submit">Consultar todas las Jaulas</button>
</form>
<br>
<br>
<div style="width: 100"></div>
<table class="table table-bordered" style="width:600px">
    <thead>
      <tr>
        <th scope="idProducto">idProducto</th>
        <th scope="idAnimal">idAnimal</th>
        <th scope="tamano">Tamaño Jaula</th>
      </tr>
    </thead>
    <tbody>
      {% for jaula in jaulas %}
        <tr>
          <td>{{ jaula.idjaula }}</td>
          <td>{{ jaula.idanimal }}</td>
          <td>{{ jaula.tamano }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}

Ghandi/logistica/templates/consultarstock.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Consultar Stock</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button id="consulta1" name="consulta1" type="submit">Consultar Producto</button>
    <br>
    <br>
    <button id="consulta2" name="consulta2" type="submit">Consultar todo el Almacén</button>
</form>
<br>
<br>
<div style="width: 100"></div>
<table class="table table-striped" style="width:600px">
    <thead>
      <tr>
        <th scope="idProducto">idProducto</th>
        <th scope="nombre">Nombre</th>
        <th scope="cantidad">Cantidad</th>
      </tr>
    </thead>
    <tbody>
      {% for producto in productos %}
        <tr>
          <td>{{ producto.idproducto }}</td>
          <td>{{ producto.nombre }}</td>
          <td>{{ producto.cantidad }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}

Ghandi/logistica/templates/hacerpedido.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Nuevo Pedido</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Hacer Pedido</button>
</form>

<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al Menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}

Ghandi/logistica/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <center> <h1> Establecimiento de conexión a la Base de Datos de Oracle </h1> </center>   
    <form method="post">  
        {% csrf_token %}
        <div class="container">
            {{ form }}
            <button type="submit">Login</button>   
        </div>
        {% if error_message %}
        <br>
        <div class="alert alert-danger">
            <center>{{ error_message }}</div></center>
        </div>
        {% endif %}
    </form>     

{% endblock content %}  

Ghandi/logistica/templates/mostrarcliente.html
{%extends 'base.html'%}

{% block content %}

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="dni">DNI</th>
        <th scope="nombre">Nombre</th>
        <th scope="apellido">Apellido</th>
        <th scope="telefono">Teléfono</th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in clientes %}
        <tr>
          <td>{{ cliente.dni }}</td>
          <td>{{ cliente.nombre }}</td>
          <td>{{ cliente.apellido }}</td>
          <td>{{ cliente.telefono }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
<center>
    <a class="btn btn-primary" href="{% url 'menu' %}" role="button">Volver al menú</a>
</center>
{% endblock%}

Ghandi/logistica/templates/vaciarjaula.html
{% extends 'base.html'%}

{% block title %}
<title>Veterinaria Ghandi - Logistica</title>
{% endblock title %}

{% block content%}
<center> <h2>Área de Logística</h2> </center>
<br>

<h3>Vaciar Jaula</h3>
<br>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Vaciar Jaula</button>
</form>

<br>
<center>
    <a class="btn btn-secondary" href="{% url 'logistica:menu_logistica' %}" role="button">Volver al Menú del Subsistema</a>
</center> 
{% if error_message %}
    <br>
    <div class="alert alert-danger">
        <center>{{ error_message }}</div></center>
    </div>
{% endif %}

{% endblock %}