Ghandi/Ghandi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include(('contabilidad.urls','contabilidad') ,namespace='contabilidad')),
    path('menu/', include(('clientes.urls', 'clientes'), namespace=   'clientes')),
    path('menu/', include(('animales.urls', 'animales'), namespace='animales')),
    path('menu/', include(('logistica.urls', 'logistica'), namespace='logistica')),
    path('menu/', include(('rh.urls', 'rh'), namespace='rh'))
]

Ghandi/contabilidad/urls.py
from django.urls import path, include
from . import views

app_name = 'contabilidad'

urlpatterns = [
    path('contabilidad/', views.menu_contabilidad, name='menu_contabilidad'),
    path('contabilidad/emitir_factura', views.emitir_factura, name='emitir_factura'),
    path('contabilidad/pagar_factura', views.pagar_factura, name='pagar_factura'),
    path('contabilidad/ingreso_salarios', views.ingreso_salarios, name='ingreso_salarios'),
    path('contabilidad/pago_pedidos', views.pago_pedidos, name='pago_pedidos'),
    path('contabilidad/pedidos_pendientes', views.pedidos_pendientes, name='pedidos_pendientes')
]

Ghandi/login/urls.py
from django.urls import path, include
from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index_login'),
    path('login/', views.login, name='login'),
    path('menu/', views.menu, name="menu"),
    path('logout/',views.logout, name="logout")
]

Ghandi/rh/urls.py
from django.urls import path, include
from . import views
app_name = 'rh'
urlpatterns = [
    path('rh/', views.menu_rh, name='menu_rh'),
    path('rh/alta_contrato', views.alta_contrato, name='alta_contrato'),
    path('rh/baja_contrato', views.baja_contrato, name='baja_contrato'),
    path('rh/agendar_entrevista', views.agendar_entrevista, name='agendar_entrevista'),
    path('rh/consultar_contrato', views.consultar_contrato, name='consultar_contrato'),
    path('rh/modificar_contrato', views.modificar_contrato, name='modificar_contrato')
]

Ghandi/contabilidad/models.py
from django.db import models

# Create your models here.

Ghandi/contabilidad/forms.py
from django import forms

class IngresoSalariosForm(forms.Form):
    dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del trabajador"}))
    
class FacturaForm(forms.Form):
    idfactura = forms.CharField(label="idFactura",widget=forms.TextInput(attrs={'placeholder': "Introduce ID de la factura"}))
    dni = forms.CharField(label="DNI",widget=forms.TextInput(attrs={'placeholder': "Introduce DNI del cliente"}))
    cantidad = forms.CharField(label="Cantidad",widget=forms.TextInput(attrs={'placeholder': "Introduce cantidad"}))

class PagoFacturaForm(forms.Form):
    idfactura = forms.CharField(label="idFactura",widget=forms.TextInput(attrs={'placeholder': "Introduce ID de la factura"}))

class PagoPedidoForm(forms.Form):
    idpedido = forms.CharField(label="idPedido",widget=forms.TextInput(attrs={'placeholder': "Introduce ID del pedido"}))

Ghandi/contabilidad/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages

from login import bd 

from .forms import IngresoSalariosForm, FacturaForm, PagoPedidoForm, PagoFacturaForm

import cx_Oracle

def menu_contabilidad(request):
    if request.method == 'POST':
        keys_request_POST = request.POST.keys()
        
        if 'emitir-factura-btn' in keys_request_POST:
            return redirect("contabilidad:emitir_factura")
        elif 'pagar-factura-btn' in keys_request_POST:
            return redirect("contabilidad:pagar_factura")
        elif 'ingreso-salarios-btn' in keys_request_POST:
            return redirect("contabilidad:ingreso_salarios")
        elif 'pago-pedidos-btn' in keys_request_POST:
            return redirect("contabilidad:pago_pedidos")
        elif 'pedidos-pendientes-btn' in keys_request_POST:
            return redirect("contabilidad:pedidos_pendientes")
        
    return render(request, 'menu_contabilidad.html')

def emitir_factura(request):
    form = FacturaForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            idfactura=form.cleaned_data["idfactura"]
            dni=form.cleaned_data["dni"]
            cantidad=form.cleaned_data["cantidad"]       
            try:
                with bd.ConnectionBD().get_conexion().cursor() as cursor:
                    # Comprobamos si el id de la factura ya existe
                    sql = "SELECT * FROM FACTURA WHERE IDFACTURA = '{0}'".format(str(idfactura))
                    cursor.execute(sql)
                    
                    if cursor.fetchone() is not None:
                        messages.error(request, '[ERROR] Ya existe una factura con el ID ingresado')
                        return render(request,"emitir_factura.html", {"form": form})
                    else:
                        # Comprobamos si el dni existe
                        sql = "SELECT * FROM CLIENTE WHERE DNI = '{0}'".format(str(dni))
                        cursor.execute(sql)
                        
                        if cursor.fetchone() is None:
                            messages.error(request, '[ERROR] No existe un cliente con el DNI ingresado')
                            return render(request,"emitir_factura.html", {"form": form})
                        else:
                            sql = "INSERT INTO FACTURA VALUES ('{0}','{1}',{2},'N')".format(str(idfactura), str(dni), str(cantidad))
                            cursor.execute(sql)
                            bd.ConnectionBD().get_conexion().commit()
                            messages.success(request, '[INFO] Factura emitida correctamente')
            except:
                messages.error(request, '[ERROR] Fallo al emitir la factura')
                return render(request,"emitir_factura.html", {"form": form})
            
    return render(request, 'emitir_factura.html',{'form':form})

def pagar_factura(request):
    form = PagoFacturaForm(request.POST)
    
    cursor = bd.ConnectionBD().get_conexion().cursor()
    if request.method == 'POST':
        if form.is_valid():
            idfactura=form.cleaned_data["idfactura"]
            sql = "SELECT PAGADO FROM FACTURA WHERE IDFACTURA = '{0}'".format(str(idfactura))
            cursor.execute(sql)
            
            consulta = cursor.fetchone()
            if consulta is not None:    
                pagado = consulta[0]
                                
                if pagado != 'S':
                    sql = "UPDATE FACTURA SET PAGADO = 'S' WHERE IDFACTURA = '{0}'".format(str(idfactura))
                    cursor.execute(sql)
                    bd.ConnectionBD().get_conexion().commit()
                    messages.success(request, '[INFO] Factura pagada correctamente')
                else:
                    messages.error(request, '[ERROR] La factura ya ha sido pagada')
                    return render(request,"pagar_factura.html", {"form": form})
            else:
                messages.error(request, '[ERROR] No existe una factura con el ID ingresado')
                return render(request,"pagar_factura.html", {"form": form})
    
    return render(request, 'pagar_factura.html',{'form':form})

def ingreso_salarios(request):
    form = IngresoSalariosForm(request.POST)
    dni=None
    sueldo=None
    if request.method == 'POST':
        if form.is_valid():
            dni=form.cleaned_data["dni"]
            
            try:
                with bd.ConnectionBD().get_conexion().cursor() as cursor:
                    sql = "SELECT SUELDO FROM CONTRATO WHERE DNI = '{0}'".format(str(dni))
                    
                    cursor.execute(sql)
                    sueldo = cursor.fetchone()

                    if sueldo is None:
                        messages.error(request, '[ERROR] No existe un contrato con el DNI ingresado')
                        return render(request,"ingreso_salarios.html", {"form": form})
                    else:
                        sueldo=sueldo[0]
            
            except:
                messages.error(request, '[ERROR] Fallo al consultar el DNI')
                return render(request,"ingreso_salarios.html", {"form": form})

    return render(request, 'ingreso_salarios.html',{'form':form, "dni": dni, "sueldo": sueldo})

def pago_pedidos(request):
    form = PagoPedidoForm(request.POST)
    
    cursor = bd.ConnectionBD().get_conexion().cursor()
    if request.method == 'POST':
        if form.is_valid():
            idpedido=form.cleaned_data["idpedido"]
            sql = "SELECT PAGADO FROM PEDIDO WHERE IDPEDIDO = '{0}'".format(str(idpedido))
            cursor.execute(sql)
            
            consulta = cursor.fetchone()
            if consulta is not None:    
                pagado = consulta[0]
                                
                if pagado != 'S':
                    sql = "UPDATE PEDIDO SET PAGADO = 'S' WHERE IDPEDIDO = '{0}'".format(str(idpedido))
                    cursor.execute(sql)
                    bd.ConnectionBD().get_conexion().commit()
                    messages.success(request, '[INFO] Pedido pagado correctamente')
                else:
                    messages.error(request, '[ERROR] El pedido ya ha sido pagado')
                    return render(request,"pagar_pedidos.html", {"form": form})
            else:
                messages.error(request, '[ERROR] No existe un pedido con el ID ingresado')
                return render(request,"pagar_pedidos.html", {"form": form})
    
    return render(request, 'pagar_pedidos.html',{'form':form})

def pedidos_pendientes(request):
    
    try:
        cursor= bd.ConnectionBD().get_conexion().cursor()
        pedidos=[]
        sql = "SELECT idpedido, cantidad, fecha, idproducto FROM pedido WHERE pagado='N'"
        cursor.execute(sql)
        pedidos = [ { 'idpedido' : fila[0], 'cantidad' : fila[1], 'fecha' : fila[2], 'idproducto' : fila[3]} for fila in cursor.fetchall() ]
    except:
        messages.error(request, '[ERROR] Fallo al consultar los pedidos pendientes')
        return render(request,"pedidos_pendientes.html")
    
    return render(request, 'pedidos_pendientes.html', {"pedidos": pedidos})

Ghandi/contabilidad/templates/base.html
<!DOCTYPE html>   
<html>   
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<title> Veterinaria Ghandi</title>  
<center><h1> Veterinaria Ghandi</h1><center>
</head>    
<body class="bg-light" >    
    
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        {{ message }}
      </div>
    {% endfor %}

    {% block content %}
    <center>
        <a class="btn btn-primary" href="login" role="button">Iniciar sesión en la BD</a>
    </center>
    {% endblock content %}

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>     
</html> 

Ghandi/contabilidad/templates/emitir_factura.html
{% extends 'base.html' %}

{% block content %}

<h2> Emitir una nueva factura </h2>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Emitir factura</button>
</form>
<br>

<center>
    <a class="btn btn-secondary" href="{% url 'contabilidad:menu_contabilidad' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/contabilidad/templates/ingreso_salarios.html
{% extends 'base.html' %}

{% block content %}

<h2>Consultar salario</h2>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Consultar salario</button>
</form>
<br>

{% if sueldo %}

    <div class="alert alert-success" role="alert">
        El sueldo del trabajador con DNI {{ dni }} es de {{ sueldo }} €
    </div>

{% endif %}

<br>
<center>
    <div>
        <a href="{% url 'contabilidad:menu_contabilidad' %}" class="btn btn-secondary" id="volver-menu-btn">Volver atrás</a>
    </div>
</center>

{% endblock %}

Ghandi/contabilidad/templates/menu_contabilidad.html
{% extends 'base.html' %}

{% block content%}
    <div style="center;"> 
        <h2>Área de Contabilidad</h2> 

        <form method="post">  
        {% csrf_token %}
        <div>
            <button class="btn btn-primary" id="emitir-factura-btn" name="emitir-factura-btn" type="submit">
                Emitir una factura
            </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="pagar-factura-btn" name="pagar-factura-btn" type="submit">
                Pagar una factura
            </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="ingreso-salarios-btn" name="ingreso-salarios-btn" type="submit">
                Ingresar salario de un trabajador
            </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="pago-pedidos-btn" name="pago-pedidos-btn" type="submit">
                Realizar el pago de un pedido
            </button>
        </div>
        <br>
        <div>
            <button class="btn btn-primary" id="pedidos-pendientes-btn" name="pedidos-pendientes-btn" type="submit">
                Consultar pedidos pendientes de pago
            </button>
        </div>
        </form> 
        <br>
        <center>
            <div>
                <a href="{% url 'login:menu' %}" class="btn btn-secondary" id="volver-menu-btn">Volver atrás</a>
            </div>
        </center>
    </div>

{% endblock %}

Ghandi/contabilidad/templates/pagar_factura.html
{% extends 'base.html' %}

{% block content %}

<h2> Pagar una factura existente </h2>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Pagar factura</button>
</form>
<br>

<center>
    <a class="btn btn-secondary" href="{% url 'contabilidad:menu_contabilidad' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/contabilidad/templates/pagar_pedidos.html
{% extends 'base.html' %}

{% block content %}

<h2> Pagar un pedido existente </h2>

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p  }}
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Pagar pedido</button>
</form>
<br>

<center>
    <a class="btn btn-secondary" href="{% url 'contabilidad:menu_contabilidad' %}" role="button">Volver al menú</a>
</center> 

{% endblock %}

Ghandi/contabilidad/templates/pedidos_pendientes.html
{% extends 'base.html' %}

{% block content %}
<h2>Consulta de pedidos pendientes</h2>

<div style="width: 100"></div>
<table class="table table-bordered" style="width:600px">
    <thead>
      <tr>
        <th scope="idpedido">idPedido</th>
        <th scope="cantidad">Cantidad</th>
        <th scope="fecha">Fecha</th>
        <th scope="idproducto">idProducto</th>
      </tr>
    </thead>
    <tbody>
      {% for pedido in pedidos %}
        <tr>
          <td>{{ pedido.idpedido }}</td>
          <td>{{ pedido.cantidad }}</td>
          <td>{{ pedido.fecha }}</td>
          <td>{{ pedido.idproducto }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<center>
    <a class="btn btn-secondary" href="{% url 'contabilidad:menu_contabilidad' %}" role="button">Volver al menú</a>
</center> 
{% endblock %}